home = ENV['HOME']
MACHINES = {
  :zfs => {
        :box_name => "generic/debian12",
        :ip => '192.168.11.11',
		:cpus => 2,
		:memory => 2048,
    }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
	  box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      (0..7).each do |i|
        box.vm.disk :disk, size: "1GB", name: "disk-#{i}"
      end
	  box.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/config.yml"
      end
    end
  end
end
