Vagrant.configure("2") do |config|

    config.vm.define "pxeserver" do |server|
      server.vm.box = 'generic/debian12'
      server.vm.disk :disk, size: "15GB", name: "extra_storage1"
    
      server.vm.host_name = 'pxeserver'
      server.vm.network :private_network, 
                         ip: "10.0.0.20", 
                         virtualbox__intnet: 'pxenet'
    
      server.vm.network "forwarded_port", guest: 80, host: 8080
      server.vm.network :private_network, ip: "192.168.11.11", adapter: 3
    
      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      end

	  server.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
	  end
	  server.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/config.yml"
      end		  
    end


end