---
- name: NGINX | Install and configure NGINX
  hosts: nginx
  become: true
  vars: Добавлена только секция vars
   nginx_listen_port: 8080

- name: NGINX | Create NGINX config file from template
  template:
   src: templates/nginx.conf.j2
   dest: /tmp/nginx.conf
  tags:
   - nginx-configuration
