MACHINES = {
  :"kernel-update" => {
              :box_name => "generic/debian12",
              :box_version => "4.3.12",
              :cpus => 2,
              :memory => 2048,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", inline: <<-SHELL
        sudo -i
        echo 'deb http://deb.debian.org/debian/ bookworm-backports main contrib non-free non-free-firmware' >> /etc/apt/sources.list
        apt update &> /dev/null
        apt install -y linux-image-6.5.0-0.deb12.4-amd64 &> /dev/null
        reboot
      SHELL
    end
  end
end
