MACHINES = {
  :"kernel-update" => {
              :box_name => "generic/debian12",
              :box_version => "4.3.12",
              :cpus => 2,
              :memory => 2048,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      (0..3).each do |i|
	  box.vm.disk :disk, size: "1GB", name: "disk-#{i}"
	  box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
      box.vm.provision "shell", inline: <<-SHELL
      SHELL
    end
  end
end
