MACHINES = {
  :inetRouter => {
        :box_name => "generic/debian12",
        :vm_name => "inetRouter",
        :net => [
                    ["192.168.255.1", 2, "255.255.255.252",  "p2p-03"],
                    ["192.168.11.11", 8, "255.255.255.0"],
                ]
  },

  :centralRouter => {
        :box_name => "generic/debian12",
        :vm_name => "centralRouter",
        :net => [
                   ["192.168.255.2",  2, "255.255.255.252",  "p2p-03"],
                   ["192.168.0.1",    3, "255.255.255.240",  "directors"],
                   ["192.168.0.33",   4, "255.255.255.240",  "office-hw"],
                   ["192.168.0.65",   5, "255.255.255.192",  "office-wifi"],
                   ["192.168.255.9",  6, "255.255.255.252",  "p2p-01"],
                   ["192.168.255.5",  7, "255.255.255.252",  "p2p-02"],
                   ["192.168.11.12", 8, "255.255.255.0"],
                ]
  },

  :centralServer => {
        :box_name => "generic/debian12",
        :vm_name => "centralServer",
        :net => [
                   ["192.168.0.2",    2, "255.255.255.240",  "directors"],
                   ["192.168.11.13", 8, "255.255.255.0"],
                ]
  },

  :office1Router => {
        :box_name => "generic/debian12",
        :vm_name => "office1Router",
        :net => [
                   ["192.168.255.10",  2,  "255.255.255.252",  "p2p-01"],
                   ["192.168.2.1",     3,  "255.255.255.192",  "dev01"],
                   ["192.168.2.65",    4,  "255.255.255.192",  "test01-srv"],
                   ["192.168.2.129",   5,  "255.255.255.192",  "managers01"],
                   ["192.168.2.193",   6,  "255.255.255.192",  "office01-hw"],
                   ["192.168.11.14", 8, "255.255.255.0"],
                ]
  },

  :office1Server => {
        :box_name => "generic/debian12",
        :vm_name => "office1Server",
        :net => [
                   ["192.168.2.130",  2,  "255.255.255.192",  "managers01"],
                   ["192.168.11.15", 8, "255.255.255.0"],
                ]
  },

  :office2Router => {
       :box_name => "generic/debian12",
       :vm_name => "office2Router",
       :net => [
                   ["192.168.255.6",  2,  "255.255.255.252",  "p2p-02"],
                   ["192.168.1.1",    3,  "255.255.255.128",  "dev02"],
                   ["192.168.1.129",  4,  "255.255.255.192",  "test02-srv"],
                   ["192.168.1.193",  5,  "255.255.255.192",  "managers02"],
                   ["192.168.11.16", 8, "255.255.255.0"],
               ]
  },

  :office2Server => {
       :box_name => "generic/debian12",
       :vm_name => "office2Server",
       :net => [
                  ["192.168.1.2",    2,  "255.255.255.128",  "dev2"],
                  ["192.168.11.17", 8, "255.255.255.0"],
               ]
  }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]

      box.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network("private_network", ip: ipconf[0], adapter: ipconf[1], netmask: ipconf[2], virtualbox__intnet: ipconf[3])
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

	  box.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
	  box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/config.yml"
      end		
      end
    end
  end
end 