VMS = {
  :nginx => {
        :box_name => "generic/debian12",
        :vm_name => "nginx",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.11.11",
  },
  :rsyslog => {
        :box_name => "generic/debian12",
        :vm_name => "rsyslog",
        :cpus => 2,
        :memory => 1024,
        :ip => "192.168.11.12",

  },
  # :elk => {
        # :box_name => "generic/debian12",
        # :vm_name => "elk",
        # :cpus => 2,
        # :memory => 4096,
        # :ip => "192.168.11.13",

  # },
}
Vagrant.configure("2") do |config|
  VMS.each do |boxname, boxconfig|
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      box.vm.network "private_network", ip: boxconfig[:ip]
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      end
	  box.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
        echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
      # box.vm.provision "shell", inline: <<-SHELL
        # mkdir -p ~root/.ssh
        # cp ~vagrant/.ssh/auth* ~root/.ssh
      # SHELL
      box.vm.provision "ansible" do |ansible|
        ansible.playbook = "ansible/config.yml"
      end		
    end
  end
end