---
# tasks file for monitor

- name: Copy network config
  template:
    src: interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644

- name: Restart service networking
  service:
    name: networking
    state: restarted
    
- name: Install packages
  apt: name={{ item }} state=latest update_cache=true
  loop: [prometheus, prometheus-alertmanager]

- name: Create prometheus config file
  template:
    src: prometheus.conf.j2
    dest: /etc/prometheus/prometheus.yml
#  notify: event_restart_prometheus

# - name: Create alert config file
  # template:
    # src: alertrules.yml
    # dest: /etc/prometheus/alert.rules.yml
 # # notify: event_restart_prometheus

- name: Start prometheus service
  service:
    name: prometheus
    state: restarted

