---
################ inetRouter ################
- name: Configure inetRouter
  hosts: inetRouter
  become: true

  tasks:
  - name: Install packages
    apt: name={{ item }} state=latest update_cache=true
    loop: [iptables, iptables-persistent]
    
  - name: Copy config iptables
    template:
      src: templates/rules.v4
      dest: /etc/iptables/rules.v4
      owner: root
      group: root
      mode: 0644
    
  - name: Copy config interfaces
    template:
      src: templates/inetRouter
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
   
  - name: Reboot
    reboot:

################ ALL ################
- name: Configure ALL
  hosts: all
  become: true

  tasks:
  - name: Execute shell commands
    shell: |
      timedatectl set-timezone Asia/Yekaterinburg
      localectl set-locale LANG=ru_RU.UTF-8
      systemctl stop vboxadd-service.service

  # - name: Set up forward packages across routers
    # sysctl:
      # name: net.ipv4.ip_forward
      # value: '1'
      # state: present
      # reload: yes
    # when: "'routers' in group_names"
    
################ Central ################    
  - name: Copy config interfaces centralRouter
    template:
      src: templates/centralRouter
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'centralRouter' in ansible_hostname"
    
  - name: Restart networks on centralRouter
    service:
      name: networking
      state: restarted
    when: "'centralRouter' in ansible_hostname"
    
  - name: Copy config interfaces centralServer
    template:
      src: templates/centralServer
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'centralServer' in ansible_hostname"
    
  - name: Restart networks on centralServer
    service:
      name: networking
      state: restarted
    when: "'centralServer' in ansible_hostname"
 
################ Office1 ################  
  - name: Copy config interfaces office1Router
    template:
      src: templates/office1Router
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'office1Router' in ansible_hostname"
    
  - name: Restart networks on office1Router
    service:
      name: networking
      state: restarted
    when: "'office1Router' in ansible_hostname"
    
  - name: Copy config interfaces office1Server
    template:
      src: templates/office1Server
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'office1Server' in ansible_hostname"
    
  - name: Restart networks on office1Server
    service:
      name: networking
      state: restarted
    when: "'office1Server' in ansible_hostname" 

################ Office2 ################  
  - name: Copy config interfaces
    template:
      src: templates/office2Router
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'office2Router' in ansible_hostname"
    
  - name: Restart networks on office2Router
    service:
      name: networking
      state: restarted
    when: "'office2Router' in ansible_hostname"
    
  - name: Copy config interfaces office2Server
    template:
      src: templates/office2Server
      dest: /etc/network/interfaces
      owner: root
      group: root
      mode: 0644 
    when: "'office2Server' in ansible_hostname"
    
  - name: Restart networks on coffice2Server
    service:
      name: networking
      state: restarted
    when: "'office2Server' in ansible_hostname" 
 
################ TEST ################ 
- name: Test access to Inernet
  hosts: servers
  become: true
  
  tasks:
  - name: Test routes
    shell:
      cmd: traceroute -m4 77.88.8.8
    register: result
    when: "'servers' in group_names"
  - name: Print traceroute
    debug:
      var: result.stdout_lines