Vagrant.configure(2) do |config|
    config.vm.box = "generic/debian12"

    config.vm.define "server" do |server|
        server.vm.hostname = "server"
        server.vm.network "private_network", ip: "192.168.11.11"
        server.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          SHELL
	    end
	end
	   
    config.vm.define "client" do |client|
        client.vm.hostname = "client"
        client.vm.network "private_network", ip: "192.168.11.12"
        client.vm.provision "shell" do |s|
          ssh_pub_key = File.readlines("/root/.ssh/id_rsa.pub").first.strip
          s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          SHELL
	    end
        
		client.vm.provision "playbook1", type:'ansible' do |ansible|
            ansible.playbook = "ansible/config.yml"
            ansible.inventory_path = "ansible/hosts"
			ansible.host_key_checking = "false"
            ansible.limit = "all"
        end

    end
end


